# Generated by Django 4.2.6 on 2023-10-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arechar_nutra", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CertificationModel",
        ),
        migrations.RemoveField(
            model_name="socialresponsibilitymodel",
            name="image",
        ),
        migrations.AddField(
            model_name="socialresponsibilitymodel",
            name="content2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="WhoAreWeModel",
        ),
    ]
